### ISSUE TITLE
在这基础上怎么能把同一个页面头部和底部能通过require进来,那就每次修改头部只需修改一个组件就完成.

### ISSUE THREAD

**Issue by Niofh** [chenli1989/webpack-MultPage-static#1]

**Comment by chenli1989** [comment]
可以参考一下这个插件html-webpack-plugin里的template配置，应该可以实现想要的效果。
插件详情：`https://github.com/jantimon/html-webpack-plugin`

**Comment by sunshinefish** [comment]
文章最后是不是还没写完？

**Comment by Niofh** [comment]
@chenli1989  网址不能访问

**Comment by chenli1989** [comment]
@Foreverofh `https://github.com/jantimon/html-webpack-plugin`

**Comment by Niofh** [comment]
不是很懂,楼主能不能把这功能加上呢!

**Comment by Niofh** [comment]
@chenli1989 为什么html不支持ejs写法呢??我改了好多地方都没有生成

**Comment by chenli1989** [comment]
@Foreverofh 建议你参考下这两个，不知能否对你有帮助
[ejs-loader](https://github.com/okonet/ejs-loader)
[ejs-compiled-loader](https://github.com/bazilio91/ejs-compiled-loader)
