### ISSUE TITLE
打包后不能识别字体文件

### ISSUE THREAD

**Issue by Niofh** [chenli1989/webpack-MultPage-static#2]
打包后不能识别字体文件，字体文件没有变成basse64位。

**Comment by chenli1989** [comment]
@Foreverofh 你请求字体文件url是否有符合这个标准呢?[webpack.config.js#L50](https://github.com/chenli1989/webpack-MultPage-static/blob/master/webpack.config.js#L50)

**Comment by Niofh** [comment]
是阿里巴巴图标库有问题 搞了我一天!
